# Google App Engine configuration (alternative to Cloud Run)
runtime: nodejs18

env_variables:
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: 1

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

handlers:
  # Handle all routes with Next.js
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

# Skip files that don't need to be uploaded
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?\.next/cache/.*$